server:
  port: 8080

spring:
  data:
    mongodb:
      database: "testdb"
      host: "localhost"
      port: 27017
      auto-index-creation: true

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG